<?php

namespace AppBundle\Repository;

/**
 * BinovalifeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BinovalifeRepository extends \Doctrine\ORM\EntityRepository
{
}
