imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

# remove next 4 lines if you are not using standard SQLite database but e.g. MySQL
# doctrine:
#     dbal:
#         # temp workaround for https://github.com/doctrine/dbal/issues/1106: define DB path here
#         path: "%kernel.root_dir%/data/dba_test.sqlite"
doctrine:
    dbal:

        # MySQL configurations

        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
web_profiler:
    # toolbar: true
    toolbar: '%kernel.debug%'
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            # level: debug
            level: info
            # channels: [!event]
        console:
            type:   console
            bubble: false
            # channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info
assetic:
    use_controller: true
#swiftmailer:
#    delivery_address: me@example.com
