# These first lines load the all routes defined as @Route() annotations in any
# controller defined inside the src/AppBundle/Controller/ directory. Controllers
# are loaded recursively, so you can separate them into subdirectories.
# If you don't like to add annotations in your applications, you can also define
# the routes in YAML, XML or PHP files.
# See http://symfony.com/doc/current/book/routing.html
app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

web:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: AppBundle:Security:login
        # template:    default/index.html.twig
        _locale:     '%locale%'

homepage:
    path: /{_locale}/web
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: AppBundle:Default:index
        # template:    default/index.html.twig
        _locale:     '%locale%'
